### ISSUE TITLE
Middle click flag

### ISSUE THREAD

**Issue by meatspinner** [soufrabi/chatbot-client#12]
I'm trying to activate middle click using the Electron flag "--enable-blink-features=MiddleClickAutoscroll" but its not working. Is it disabled in the code?

**Comment by soufrabi** [comment]
Currently, the flags are hardcoded. However, it should not be. Thanks for reporting the issue. I will see to it.

**Comment by soufrabi** [comment]
v1.0.8 should fix this
currently being dealt with in https://github.com/flathub/io.github.anirbandey1.ChatbotClient/pull/11

now you can use also set ADDITIONAL_FLAGS environment variable to enable a particular flag permanently 
check this [file](https://github.com/soufrabi/chatbot-client/blob/main/assets/chatbot-client) to see how flags are being applied

**Comment by soufrabi** [comment]
However, i am not sure if the middle click feature will work. try and see.
make sure to run `flatpak run app-id` in a terminal to see which flags are being applied

**Comment by meatspinner** [comment]
Its working as intended, thanks.
