### ISSUE TITLE
APP DOESNT PROMPT FOR PASSWORD

### ISSUE THREAD

**Issue by DEGENMUTANT** [soufrabi/chatbot-client#15]
App Doesnt WORK

**Comment by soufrabi** [comment]
Try clearing the cache 
Press Alt key, Top Menu -> File- >Clear App Data

or, preferably by using the following command
```sh
rm -rf ~/.var/app/io.github.anirbandey1.ChatbotClient
```
then relaunch the app.

Ctrl+Shift+i opens the developer tools check if shows anything.

Since the issue has not been resolved it would have been better to just keep it open.

**Comment by soufrabi** [comment]
This issue was most probably related permissions. I have resolved this in a ubuntu 22.04 lxd vm 
basically it needs access to dbus 

Check this

![2024-01-31_08-50](https://github.com/soufrabi/chatbot-client/assets/116617392/cb4348a4-e35d-4a35-932d-161e819af467)

**Comment by soufrabi** [comment]
Its not a good idea to use system-bus permission on regular apps. So, perhaps deprecating the app is next logical step.
