### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by kyouhan** [soufrabi/chatbot-client#4]
I use Fedora39
The app doesn't start, just crashes
Here is the details from Problem Reporting app (there is a problem reporting the issue from the app)
![Screenshot from 2023-12-23 16-00-09](https://github.com/soufrabi/chatbot-client/assets/152380027/4f001e61-1d71-4ad6-afbb-c68ff456e38b)

**Comment by soufrabi** [comment]
Thank you for reporting the problem. Please check if v1.0.6 (latest) version of the app is working properly. It should be available shortly. Just run 
```sh
flatpak update
```
and then try to launch the app

**Comment by o0nd7ots** [comment]
@kyouhan does that still happen?

**Comment by DEGENMUTANT** [comment]
just download Chatgpt Electron and i promis you wont face the issues we are all facing with this app , I use Ubuntu and is Crashes and doesnt work for me neither, they puttting a bad taste in people mouth that love flatpaks.. But yeah if you guys want a Chatgpt Desktop Appllication , head over to Software center and download ChatGPT Electron by: Nikola ,  that way you dont have to worry about chatbotClient issues, and plus Nikola application is very minimal in storage usage compare to chatbotClient.. GoodLuck.

**Comment by soufrabi** [comment]
I believe his problem was due to  https://github.com/soufrabi/chatbot-client/issues/3  with ozone wayland flags

**Comment by soufrabi** [comment]
@DEGENMUTANT  a little more info
such as `flatpak run` output and whether you are in wayland /x11 session would help.
I apologize for the inconvenience you faced.
