### ISSUE TITLE
Missing a dependency ? (org.freedesktop.Platform)

### ISSUE THREAD

**Issue by ImAReplicant** [soufrabi/chatbot-client#8]
After entering my email address to log in, I get a blank screen.

I think the flatpak package is missing a dependency, because when I install `org.freedesktop.Platform 23.08` manually, the problem is solved.

**Comment by soufrabi** [comment]
Please provide the information about the distro you are using 
are you using wayland or xorg 
so i can try to reproduce the issue.

**Comment by ImAReplicant** [comment]
Oh sorry, I thought the distro didn't matter for a flatpak.
Anyway, my distro is NixOS and I use xorg.

**Comment by soufrabi** [comment]
Earlier the app was using `org.freedesktop.Platform`  version 22.08 which could have caused this issue. The latest release uses version `org.freedesktop.Platform`  23.08. So, the issue should be resolved now.

**Comment by ImAReplicant** [comment]
Confirmed. The update to the latest release has resolved the issue. Marking it as resolved
